### ISSUE TITLE
当 width > 1100px 时，blockquote 嵌套时会出现 BUG

### ISSUE THREAD

**Issue by linkgod** [lepture/yue.css#2]
当 width > 1100px 时，blockquote 出现嵌套时，子 blockquote 缩进不正常

BUG重现 [http://cdpn.io/roizd](http://cdpn.io/roizd)

当 width < 1100px 的时候不会出现此 BUG

问题代码应该是这段，应该如何优化它？

``` css
.yue blockquote {
    margin-left: -24px;
    padding-left: 20px;
    border-width: 4px;
  }
```
